# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
custom_fields:
  gr_account_number:
  shelf: read
  layout: large
  layout_number_of_books: 3

time_zone: Europe/Berlin

# override variables
variables:
  trmnl:
    user:
      name: John Smith
      first_name: John
      last_name: Smith
      locale: en
      time_zone: "Atlantic Time (Canada)"
      time_zone_iana: "America/Halifax"
      utc_offset: -10800
    device:
      friendly_id: ABCDEF
      percent_charged: 70.83
      wifi_strength: 50
      height: 480
      width: 800
    system:
      timestamp_utc: 1760189898
    plugin_settings:
      instance_name: Goodreads
      strategy: polling
      dark_mode: 'no'
      no_screen_padding: 'no'
      polling_headers: ''
      polling_url: ''
  rss: {
  "channel": {
    "ttl": "60",
    "item": {
      "book": {
        "id": "44147078",
        "num_pages": "687"
      },
      "guid": "https://www.goodreads.com/review/show/3465182341?utm_medium=api&utm_source=rss",
      "isbn": "0241373344",
      "link": "https://www.goodreads.com/review/show/3465182341?utm_medium=api&utm_source=rss",
      "title": "The Secret Commonwealth (The Book of Dust #2)",
      "book_id": "44147078",
      "pubDate": "Sat, 18 Oct 2025 06:32:12 -0700",
      "user_name": "Pascal",
      "author_name": "Philip Pullman",
      "description": "\n      \n      <a href=\"https://www.goodreads.com/book/show/44147078-the-secret-commonwealth?utm_medium=api&amp;utm_source=rss\"><img alt=\"The Secret Commonwealth (The Book of Dust #2)\" src=\"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1567597032l/44147078._SY75_.jpg\" /></a><br/>\n                                      author: Philip Pullman<br/>\n                                      name: Pascal<br/>\n                                      average rating: 3.92<br/>\n                                      book published: 2019<br/>\n                                      rating: 5<br/>\n                                      read at: 2020/09/08<br/>\n                                      date added: 2025/10/18<br/>\n                                      shelves: read<br/>\n                                      review: <br/><br/>\n                                      \n    ",
      "user_rating": "5",
      "user_review": null,
      "user_read_at": "Tue, 8 Sep 2020 00:00:00 +0000",
      "user_shelves": "read",
      "average_rating": "3.92",
      "book_image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1567597032l/44147078._SY75_.jpg",
      "book_published": "2019",
      "user_date_added": "Sat, 18 Oct 2025 06:32:12 -0700",
      "book_description": "It is twenty years since the events of <i>La Belle Sauvage: The Book of Dust Volume One</i> unfolded and saw the baby Lyra Belacqua begin her life-changing journey.<br /><br />It is seven years since readers left Lyra and the love of her young life, Will Parry, on a park bench in Oxford's Botanic Gardens at the end of the ground-breaking, bestselling His Dark Materials sequence.<br /><br />Now, in <i>The Secret Commonwealth</i>, we meet Lyra Silvertongue. And she is no longer a child . . .<br /><br />The second volume of Sir Philip Pullman's The Book of Dust sees Lyra, now twenty years old, and her daemon Pantalaimon, forced to navigate their relationship in a way they could never have imagined, and drawn into the complex and dangerous factions of a world that they had no idea existed.<br /><br />Pulled along on his own journey too is Malcolm; once a boy with a boat and a mission to save a baby from the flood, now a man with a strong sense of duty and a desire to do what is right.<br /><br />Theirs is a world at once familiar and extraordinary, and they must travel far beyond the edges of Oxford, across Europe and into Asia, in search for what is lost - a city haunted by daemons, a secret at the heart of a desert, and the mystery of the elusive Dust.",
      "user_date_created": "Mon, 27 Jul 2020 13:36:57 -0700",
      "book_large_image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1567597032l/44147078._SY475_.jpg",
      "book_small_image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1567597032l/44147078._SY75_.jpg",
      "book_medium_image_url": "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1567597032l/44147078._SX98_.jpg"
    },
    "link": [
      "https://www.goodreads.com/review/list_rss/72090802?shelf=read",
      {
        "rel": "self",
        "href": "https://www.goodreads.com/review/list_rss/72090802?shelf=read",
        "type": "application/rss+xml"
      }
    ],
    "meta": {
      "name": "robots",
      "content": "noindex"
    },
    "image": {
      "url": "https://www.goodreads.com/images/layout/goodreads_logo_144.jpg",
      "link": "https://www.goodreads.com/review/list_rss/72090802?shelf=read",
      "title": "Pascal's bookshelf: read",
      "width": "144",
      "height": "41"
    },
    "title": "Pascal's bookshelf: read",
    "language": "en-US",
    "copyright": "Copyright (C) 2025 Goodreads Inc. All rights reserved.\n    ",
    "description": "Pascal's bookshelf: read",
    "lastBuildDate": "Sat, 18 Oct 2025 06:32:12 -0700"
  },
  "version": "2.0"
}
